mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "example"
  database: "bedwars"
  ssl: false

menus:
  items:
    previous:
      type: "ARROW"
      name: "&cPrevious page"
      lore:
        has:
          - "&7Click to go to page &c%page%&7/&c%pages%&7."
        has_not:
          - "&cYou are on the first page."
    next:
      type: "ARROW"
      name: "&aNext page"
      lore:
        has:
          - "&7Click to go to page &c%page%&7/&c%pages%&7."
        has_not:
          - "&cYou are on the last page."

    custom:
      '#':
        type: "BLACK_STAINED_GLASS_PANE"
        name: "&r"

  setup:
    title: "&7Arena Setup"
    structure:
      - "# # # # # # # # #"
      - "# . . . . . . . #"
      - "# . . . . . . . #"
      - "# . . . . . . . #"
      - "# # # # # # # # #"

messages:
  prefix: "&c&lBed&f&lWars &f&l» &7"
  not-found: "&cThe command you entered was not found."
  only-players: "&cOnly players can use this command."
  no-permission: "&cYou do not have permission to use this command."
  invalid-usage: "&7Invalid usage. Please use &c&n%usage%&7."
  error: "&cAn error occurred while executing this command. Error: %error%"
  reload: "&7The plugin has been reloaded."
  world-not-found: "&cThe world you entered was not found."
  setup-started: "&7The setup has started."