mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "example"
  database: "bedwars"
  ssl: false

menus:
  items:
    setup:
      arenas:
        type: "DIAMOND_SWORD"
        name: "&7Set Arenas"
        lore:
          - "&7Click to &c&nset&7 the &c&narena count&7."

      min-players:
        type: "ENDER_PEARL"
        name: "&7Set Min Players"
        lore:
          - "&7Click to &c&nset&7 the &c&nrequired players&7."

      team-players:
        type: "MAGMA_CREAM"
        name: "&7Set Team Players"
        lore:
          - "&7Click to &c&nset&7 the &c&nplayers per team&7."

      teams:
        type: "DIAMOND"
        name: "&7Setup Teams"
        lore:
          - "&7Click to &c&nsetup&7 the &cteams&7."

      spectators:
        type: "ENDER_EYE"
        name: "&7Setup Spectators"
        lore:
          - "&7Click to &c&nsetup&7 the &cspectators location&7."

      save:
        type: "EMERALD"
        name: "&aSave"
        lore:
          - "&7Click to &asave &7the &asettings&7."

      team-color:
        type: "WOOL"
        name: "%color_display%%color% &7Team"
        lore:
          - "&7Click to &c&nedit&7 the &cteam&7."

      team-spawn:
        type: "GOLD_BLOCK"
        name: "&7Set Spawn"
        lore:
          - "&7Click to &c&nset&7 the &cspawn location&7."

      team-bed:
        type: "BED"
        name: "&7Set Bed"
        lore:
          - "&7Click to &c&nset&7 the &cbed location&7."

      team-shop:
        type: "CHEST"
        name: "&7Set Shop"
        lore:
          - "&7Click to &c&nset&7 the &cshop location&7."

      team-upgrades:
        type: "ANVIL"
        name: "&7Set Upgrades"
        lore:
          - "&7Click to &c&nset&7 the &cupgrades location&7."

      team-generator:
        type: "FURNACE"
        name: "&7Set Generator"
        lore:
          - "&7Click to &c&nset&7 the &cgenerator location&7."

      generator:
        type: "FURNACE"
        name: "&7Set Generator"
        lore:
          - "&7Click to &c&nset&7 a &cgenerator location&7."

      generators:
        type: "FURNACE"
        name: "&7Edit Generators"
        lore:
          - "&7Click to &c&nedit&7 the &cgenerators&7."

    previous:
      type: "ARROW"
      name: "&cPrevious page"
      lore:
        has:
          - "&7Click to go to page &c%page%&7/&c%pages%&7."
        has_not:
          - "&cYou are on the first page."
    next:
      type: "ARROW"
      name: "&aNext page"
      lore:
        has:
          - "&7Click to go to page &c%page%&7/&c%pages%&7."
        has_not:
          - "&cYou are on the last page."

    custom:
      '#':
        type: "BLACK_STAINED_GLASS_PANE"
        name: "&r"

  setup:
    main:
      title: "&7Arena Setup"
      structure:
        - "# # # # # # # # #"
        - "# . A . M . T . #"
        - "# . . G L E . . #"
        - "# . . . S . . . #"
        - "# # # # # # # # #"

    teams:
      title: "&7Select Team"
      structure:
        - "# # # # # # # # #"
        - "# . . . . . . . #"
        - "# . . . . . . . #"
        - "# . . . . . . . #"
        - "# # # # # # # # #"

    team:
      title: "&7Team Setup"
      structure:
        - "# # # # # # # # #"
        - "# . S . B . s . #"
        - "# . . U . G . . #"
        - "# . . . F . . . #"
        - "# # # # # # # # #"

    generators:
      title: "&7Edit Generators"
      structure:
        - "# # # # # # # # #"
        - "# . . . . . . . #"
        - "# . . . . . . . #"
        - "# . . . . . . . #"
        - "# # # # # # # # #"

messages:
  prefix: "&c&lBed&f&lWars &f&l» &7"
  not-found: "&cThe command you entered was not found."
  only-players: "&cOnly players can use this command."
  no-permission: "&cYou do not have permission to use this command."
  invalid-usage: "&7Invalid usage. Please use &c&n%usage%&7."
  invalid-number: "&cThe number you entered is invalid."
  error: "&cAn error occurred while executing this command. Error: %error%"
  reload: "&7The plugin has been reloaded."
  world-not-found: "&cThe world you entered was not found."
  setup-started: "&7The setup has started."
  game-not-found: "&cCannot find a game for you!"
  game-full: "&cThe game is full."

  setup:
    arenas: "&7Please enter the &c&narena count&7."
    min-players: "&7Please enter the &c&nrequired players&7."
    team-players: "&7Please enter the &c&nplayers per team&7."
    complete: "&7The setup has been completed."
    incomplete: "&7The setup is incomplete. Please complete the setup."

  titles:
    start-countdown:
      title: "&c%time%"
      subtitle: "&7until the game starts."