name: Bedwars
version: @version@
main: me.lorenzo0111.bedwars.BedwarsPlugin
api-version: '1.13'
authors: [ Lorenzo0111 ]
depend:
  - SlimeWorldManager
softdepend:
  - DecentHolograms
  - PlaceholderAPI
commands:
  bedwars:
    aliases:
      - bw